### ISSUE TITLE
Some references broken

### ISSUE THREAD

**Issue by smakhtin** [elliotwoods/VVVV.Packs.Image#1]
Native binaries references broken for OpenCV, EDSDK and FreeImage. Found, that this references was just gitignored.
Managed binaries references broken for FlyCapture, OpenNI.

**Comment by elliotwoods** [comment]
so by 'broken' you mean 'missing dll'?
will add immediately

**Comment by elliotwoods** [comment]
native broken for OpenCV is a bit tricky. i might zip these up for the time being as they're huge and don't want them in the repo. Also these dll's are likely to change a lot (and also we're looking at using much smaller dll's), so doesn't make much sense to add them to the repo right now.

**Comment by smakhtin** [comment]
Yes, looks like dlls missing. I already fixed OpenCV, and ignored another projects, bcs currently don't need it. Maybe we should put OpenCV dll's as separate download, hosted on dropbox and just add initialization script. I can make this.

**Comment by elliotwoods** [comment]
hmm
i need to reinstall visual studio 2010 before i can test it 
will push what changes i have now

re: initialisation script - that'd be great
curl comes with the git mini-sys, so you can use that to do the download

elliot

**Comment by elliotwoods** [comment]
ok, i've added edsdk, freeimage, flycapture
openni should be using the dll's from the openni plugin which is inside the addonpack (i.e. to make sure it uses same version of openni)

**Comment by smakhtin** [comment]
Don't know what with openNI, but currenty in VS it looks like missing. I'm building it from the same dirrectory structure, that you suggested.

**Update:**
Checked your last commit, all is working, OpenNI is missing OpenNI.Net

**Comment by elliotwoods** [comment]
i don't include OpenNI.Net to retain compatability with the addonpack (which has its own version).
thanks for flagging all this.
i'm marking as resolved
