### ISSUE TITLE
Missing OpenCV.dll Beta30.2

### ISSUE THREAD

**Issue by timpernagel** [elliotwoods/VVVV.Packs.Image#12]
Hey Elliot,

i'm trying to get the VVVV.Packs.Image working, but still getting red nodes.
I've copied the pack in the packs-folder of the 30.2 and linked the nodes folder in the root-patch, like mentioned here: http://vvvv.org/contribution/vvvv.packs.image but without any success. I've also downloaded the EmugCV-dlls and put it in the x86 folder as you've wrote in the Readme.

![image 2013-07-24 at 5 00 50 pm](https://f.cloud.github.com/assets/4920332/849381/880b887e-f473-11e2-8b6c-49b37bb5a8ce.png)

The old imagepack of the contribution-link works pretty good, for the github-version all the pipet, astexture, etc. nodes are missing.

 Do i' ve have to recompile the opencv.dll? What is the trick?

Cheers,
Johannes

**Comment by smakhtin** [comment]
Here you can find my working build, that i'm currently using for project https://www.dropbox.com/sh/3e22m270vpidgm5/bUHeCu3qpp

**Comment by timpernagel** [comment]
Thanks!

**Comment by elliotwoods** [comment]
I'm chalking this up as bad documentation of installation instructions. moving to:
https://github.com/elliotwoods/VVVV.Packs.Image/issues/22
