### ISSUE TITLE
how to compile ...

### ISSUE THREAD

**Issue by sebllll** [elliotwoods/VVVV.Packs.Image#13]
i did the following things (iirc)
- downloaded the repo
- placeed the repo in the vvvv45 folder in my vvvv-sdk folder (so vs finds all the references)
- manually added the feraltic and dx11 references (i had them already compiled, but the delivered ones should work, too)
- downloaded openni from https://github.com/OpenNI and compiled it. then, one can fix the missing openni.net reference by adding the compiled one from myFolder\OpenNI\Platform\Win32\Build\Wrappers\OpenNI.net\obj\x86\Release\OpenNI.Net.dll
- fixed some minor things that threw errors. i pushed that ones here: https://github.com/sebllll/VVVV.Packs.Image/commit/d6feeb0e56af426c7919561a59a9c4184f750bb3
- turned on "Allow unsafe Code" in Decklinks properties
- added the CLeye csproj to the solution

**Comment by joreg** [comment]
the one thing i had to do from sebls branch is getting:
http://sourceforge.net/projects/emgucv/files/latest/download?source=files

and putting the \bin\x86 and \bin\x64 from this download into
src\nodes\plugins\Image\OpenCV\Dependencies\OpenCV

as mentioned here:
https://github.com/sebllll/VVVV.Packs.Image/tree/master/src/nodes/plugins/Image/OpenCV/Dependencies/OpenCV/x86

**Comment by elliotwoods** [comment]
merging this with issue 
https://github.com/elliotwoods/VVVV.Packs.Image/issues/22

it might be best to make an install script
anyway, the readme will make this more clear in future
