### ISSUE TITLE
SolvePnP vs. FindExtrinsics

### ISSUE THREAD

**Issue by joreg** [elliotwoods/VVVV.Packs.Image#19]
those two nodes have exactly the same signature of inlets and outlets. also internally they are calling the same opencv function. they only seem to do errorhandling a bit differently. 

is there a reason to keep both? FindExtrinsics is definitely the better name in case you can get rid of one.

**Comment by elliotwoods** [comment]
Agreed, noted this myself. Will combine.
To note, FindExtrinsics is a more descriptive name, but is the old OpenCV naming scheme (SolvePnP is the new naming scheme), so I might go for SolvePnP with FindExtrinsics and other notes in Tags for the node
