### ISSUE TITLE
VideoIn (OpenCV DirectShow) not disposed correctly

### ISSUE THREAD

**Issue by smakhtin** [elliotwoods/VVVV.Packs.Image#2]
If you create node VideoIn (OpenCV DirectShow), activate a camera and then delete it, camera will still be active. I checked the Dispose method of instance, and looks like it empty.

**Comment by elliotwoods** [comment]
ah ok
i can recreate here
will fix on next vvvv coding session

**Comment by smakhtin** [comment]
Ok, i'm just keeping here the track of bugs, so if i fix it arly, i will close issue and make a pull commit.

**Comment by elliotwoods** [comment]
perfect!

**Comment by elliotwoods** [comment]
another one which seems to have been fixed in the interim period
closing.
