### ISSUE TITLE
Chessboard.tfx

### ISSUE THREAD

**Issue by circuitb** [elliotwoods/VVVV.Packs.Image#20]
ai Elliot
the Chessboard.tfx inside
https://github.com/elliotwoods/VVVV.Packs.Image/blob/master/lib/nodes/modules/Image/OpenCV/DX11/Chessboard%20(DX11.Layer).v4p
 doesn't draw the full chessboard and the BoardSize XY pin doesn't do anything

**Comment by elliotwoods** [comment]
will look into
