### ISSUE TITLE
suggested renamings

### ISSUE THREAD

**Issue by joreg** [elliotwoods/VVVV.Packs.Image#23]
with textureFX we have nodes with either version: Source, Filter, Analysis, Mixer

accordingly i suggest to add the version "Filter" to the following nodes:
Canny, Erode, Sobel, Dilate, Grayscale, GaussianBlur, ConvertScale, FrameDifference, Average

for ConvertScale also add "contrast" as tag as that is essentially a contrasting function or not? or even rename the node to Contrast ()?

and "Analysis" to:
Contour
Change
Framerate
Pipet

and rename: Noise (OpenCV Generator) -> Noise (OpenCV Source)

and rename: AvgSdv (OpenCV Mean) -> Average (OpenCV Analysis)
so there will be:
 Average (OpenCV Analysis) 
and 
 Average (OpenCV Filter)

also: <, =, >, WithinRange have ", Scalar" in their version. the "," is forbidden at all and i'd also suggest to remove the "Scalar" since there is no chance of confusing them with similarly named nodes yet anyway.

**Comment by joreg** [comment]
some more:

ImageResize (OpenCV) -> Resize (OpenCV)
Rotate (OpenCV Step) -> Rotate (OpenCV)
Rotate (OpenCV Continuous) -> Transform (OpenCV)

**Comment by joreg** [comment]
tags:

Not: invert
Canny, Sobel: edge
Erode, Dilate: morphology, noise

**Comment by elliotwoods** [comment]
if we add a Scalar into name later, would that break the node in old patches? (with a quick doubleclick->replace->auto-relink)

**Comment by joreg** [comment]
ja, would break but could be easily relinked as you lined out. question would be if you really have other nodes you'd name the same, why not give a version to those..

**Comment by elliotwoods** [comment]
ok sure :)

**Comment by elliotwoods** [comment]
this is done
along with a pretty significant rename.,,,,

**Comment by joreg** [comment]
and more:
how about making 4 categories
- CV (for basic stuff)
- CV.Image (for filters, analysis, source)
- CV.Transform (for all calib stuff that returns transforms)
- CV.StructuredLight

**Comment by elliotwoods** [comment]
soo... all the help patches have to change again and the code and the help patch file names....

**Comment by elliotwoods** [comment]
i.e. you sure this is the right way?

**Comment by elliotwoods** [comment]
complete
