### ISSUE TITLE
Hungry

### ISSUE THREAD

**Issue by elliotwoods** [elliotwoods/VVVV.Packs.Image#28]
To recreate:
- Have lunch at 1pm (before joreg wakes up)

Proposed fix required...

contributors : @joreg @azeno @gregsn

**Comment by joreg** [comment]
uff..actually i am thinking of a pizza right now. who's in?

**Comment by elliotwoods** [comment]
- [x] pizza
- [ ] curry
- [ ] german
- [ ] something else

**Comment by joreg** [comment]
don't give people choices...they might just take them. PIZZA it iS!!!
