### ISSUE TITLE
VideoIn (OpenCV DirectShow) need automatic reinitialisation after resolution change.

### ISSUE THREAD

**Issue by smakhtin** [elliotwoods/VVVV.Packs.Image#3]
When you change input resolution, node just stops working - needs disable-enable trick.

**Comment by elliotwoods** [comment]
so this should be fixed by proper use of Reinitialize. I'll aim to fix this in the new Beta with a new pattern (with stricter usage)

**Comment by elliotwoods** [comment]
not able to recreate here.
closing for now. i'm sure that the bug will come back at some point but it's working correctly in the current codebase
