### ISSUE TITLE
filter nodes don't show their tags

### ISSUE THREAD

**Issue by joreg** [elliotwoods/VVVV.Packs.Image#35]
some of the filter nodes have tags, but none of them are shown in the nodebrowser right now. related to your inheritance scheme?!

also they all should get the "filter" tag

**Comment by elliotwoods** [comment]
which inheritance are you referring to?

**Comment by joreg** [comment]
the c#-class inheritance... was just a wild guess without any specific idea

**Comment by joreg** [comment]
tags are now showing in latest build.

**Comment by elliotwoods** [comment]
Great that all these are fixed
Thank you vadim!

## 

Typed by touchscreen

Elliot Woods
elliot@KimchiAndChips.com

UK : +447944977628
KR : +821034458086
