### ISSUE TITLE
2 average nodes

### ISSUE THREAD

**Issue by joreg** [elliotwoods/VVVV.Packs.Image#36]
they are both in the same category now and not distinguished by version. i tried to distinguish by version but still only one shows up, not sure why.

i suggest the second one getting Version = "Temporal"

**Comment by elliotwoods** [comment]
fixed (by you i think)

**Comment by joreg** [comment]
no, still the same. only one Average (CV.Image) shows up.

**Comment by joreg** [comment]
seems fixed in latest build.
