### ISSUE TITLE
2 opticalflow nodes

### ISSUE THREAD

**Issue by joreg** [elliotwoods/VVVV.Packs.Image#37]
they have their version set, but it doesn't show.. same as with https://github.com/elliotwoods/VVVV.Packs.Image/issues/36 then i guess

**Comment by elliotwoods** [comment]
not sure about this one
i'm only getting 1 optical flow node appearing in the list, and it's missing its version name :(
is this a VVVV API bug?

**Comment by joreg** [comment]
true, in latest build i only get one as well..hm..

**Comment by joreg** [comment]
seems fixed in latest build
