### ISSUE TITLE
Cons (CV.Image) doesn't seem to work

### ISSUE THREAD

**Issue by joreg** [elliotwoods/VVVV.Packs.Image#38]
tested with the girlpower\Basics.v4p patch and HEAD
always only returns NIL

**Comment by elliotwoods** [comment]
can duplicate here (added a cons help patch)
whilst at Praxis I switched over from:

https://github.com/elliotwoods/VVVV.Packs.Image/blob/48e13162cd0b05b600c9acf66047da6dde90ef41/src/nodes/plugins/Image/OpenCV/src/MultiInput/Cons.cs

to

https://github.com/elliotwoods/VVVV.Packs.Image/blob/a2f240d6dfdd352aa2328e64c0fd10726264d629/src/nodes/plugins/Image/OpenCV/src/MultiInput/Cons.cs

(i.e. i'm using the templated type from VVVV.Nodes)

is there any reason why the templated Cons node wouldn't work with CVImageLink? (as can be seen in the previous version, there's nothing particularly special required with Cons'ing CVImageLink types).

**Comment by smakhtin** [comment]
Looks like i even can't compile it currently.

**Comment by elliotwoods** [comment]
Screenshots?

Typed by touchscreen
