### ISSUE TITLE
ImageLoad (OpenCV FreeImage) don't push image upstream after patch reloading.

### ISSUE THREAD

**Issue by smakhtin** [elliotwoods/VVVV.Packs.Image#4]
If you have this node in patch, save it, close and open again this node stops pushing image data to other node - solved by pressing reload, so we need to do this automatically.

**Comment by elliotwoods** [comment]
i think there's something deeper going on with this (e.g. the first image to be sent through the double-buffer chain gets ignored, or the image is sent before the connection is made). 

ImageLoad is revealing a lot of the bugs right now.

**Comment by elliotwoods** [comment]
Checked both ImageLoads (original OpenCV version and FreeImage version).

Both now working fine when reloading patch, and also tested when loading patch on startup.

They have the same internal code (up to the point where the filename gets exchanged for an image in the instance).
